version: '3.3'

volumes:
  pg_data:
  frontfiles:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    ports:
       - "5432:5432/tcp"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    image: evkasonka/foodgram_backend
    env_file: ../.env
    command: bash -c "python manage.py collectstatic --no-input &&
                      mkdir -p /backend_static/static &&
                      cp -r /app/collected_static/. /backend_static/static/ &&
                      python manage.py makemigrations &&
                      python manage.py migrate &&
                      gunicorn foodgram.wsgi -b 0.0.0.0:8000"
    volumes:
      - frontfiles:/backend_static/
      - media:/app/media/
    restart: always
    depends_on:
      - db
  frontend:
    image: evkasonka/foodgram_frontend
    volumes:
      - frontfiles:/app/build/
      
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontfiles:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/media/
    depends_on:
      - backend
      - frontend

