# Generated by Django 4.2.4 on 2023-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default=None,
                help_text="Картинка, закодированная в Base64",
                null=True,
                upload_to="recipes/",
                verbose_name="Картинка",
            ),
        ),
    ]
