# Generated by Django 4.2.4 on 2023-09-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamountinrecipe',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientAmountInRecipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
