# Generated by Django 4.2.4 on 2023-09-05 20:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_alter_ingredientamountinrecipe_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientamountinrecipe",
            name="amount",
            field=models.PositiveSmallIntegerField(
                help_text="Количество",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Минимальное количество ингредиента = 1."
                    )
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientamountinrecipe",
            name="recipe",
            field=models.ForeignKey(
                help_text="Рецепт",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredienе_amount_in_recipe",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientamountinrecipe",
            constraint=models.UniqueConstraint(
                fields=("ingredient", "recipe"), name="unique_ingredient_recipe"
            ),
        ),
        migrations.AddConstraint(
            model_name="isfavorited",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_favorute_recipe"
            ),
        ),
        migrations.AddConstraint(
            model_name="isinshoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_shopping_cart"
            ),
        ),
    ]
