# Generated by Django 4.2.4 on 2023-09-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_alter_ingredientamountinrecipe_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientamountinrecipe",
            name="recipe",
            field=models.ForeignKey(
                help_text="Рецепт",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_amount_in_recipe",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
    ]
